export default {
  games: [
    // LOL ROSTER //

    {
      game: "lol",
      teams: [
        {
          name: "lolTeam",
          players: [
            {
              pseudo: "RAI",
              nom: "-",
              prenom: "Yacine",
              dateOfBirth: {
                year: 1995,
                month: 8,
                day: 3,
              },
              character: "lol/renekton.jpg",
              elo: "platinium",
              fonction: "Toplane",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "HUNTT",
              nom: "Hours",
              prenom: "Joan",
              dateOfBirth: {
                year: 1996,
                month: 4,
                day: 16,
              },
              character: "lol/zac.jpg",
              elo: "diamond",
              fonction: "Jungle",
              avatar: "lol/misae.png",
              twitterLink: "https://twitter.com/HunttAMV",
              ytbLink: "https://www.youtube.com/user/HunttWithStyle",
              twitchLink: "https://www.twitch.tv/hunttamv",
              igLink: "",
            },
            {
              pseudo: "XAIRO",
              nom: "Fichot",
              prenom: "Benjamin",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "lol/yasuo.jpg",
              elo: "platinium",
              fonction: "Midlane",
              avatar: "lol/xairo.jpg",
              twitterLink: "https://twitter.com/MrKyo1",
              ytbLink: "",
              twitchLink: "https://www.twitch.tv/xairotv",
              igLink: "",
            },
            {
              pseudo: "MISAE",
              nom: "Pailloux",
              prenom: "Océane",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 2,
              },
              character: "lol/ezreal.jpg",
              elo: "diamond",
              fonction: "AdCarry",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "DAGREN",
              nom: "Hours",
              prenom: "Jeremy",
              dateOfBirth: {
                year: 1998,
                month: 9,
                day: 6,
              },
              character: "lol/thresh.jpg",
              elo: "platinium",
              fonction: "Support",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
          ],
        },
      ],
    },

    // ROCKET LEAGUE ROSTER //

    {
      game: "rocketleague",
      teams: [
        {
          name: "rlTeam",
          players: [
            {
              pseudo: "Mablo",
              nom: "Blouet",
              prenom: "Arthur",
              dateOfBirth: {
                year: 1998,
                month: 5,
                day: 7,
              },
              character: "rl/octane-mablo.jpg",
              peak: 1650,
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "Infinity_RL",
              nom: "-",
              prenom: "-",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "rl/octane-infinity.jpg",
              peak: 1565,
              fonction: "Joueur (c)",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "Saumon",
              nom: "Carceller",
              prenom: "Erwann",
              dateOfBirth: {
                year: 2003,
                month: 6,
                day: 19,
              },
              character: "rl/octane-saumon.jpg",
              peak: 1565,
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
          ],
        },
      ],
    },

    // VALORANT ROSTER //

    {
      game: "valorant",
      teams: [
        {
          name: "valorantTeam",
          players: [
            {
              pseudo: "Mablo",
              nom: "-",
              prenom: "-",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "lol/renekton.jpg",
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "Infinity_RL",
              nom: "-",
              prenom: "-",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "lol/renekton.jpg",
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "Saumon",
              nom: "-",
              prenom: "-",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "lol/renekton.jpg",
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
          ],
        },
      ],
    },

    // FORTNITE ROSTER //

    {
      game: "ftn",
      teams: [
        {
          name: "ftnTeam",
          players: [
            {
              pseudo: "Reyxzo",
              nom: "Drn",
              prenom: "Thomas",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "ftn/dynamo.jpg",
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "MC Guigui",
              nom: "Cholewa",
              prenom: "Guillaume",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "ftn/dynamo.jpg",
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
            {
              pseudo: "James",
              nom: "-",
              prenom: "-",
              dateOfBirth: {
                year: 1996,
                month: 9,
                day: 20,
              },
              character: "ftn/dynamo.jpg",
              fonction: "Joueur",
              avatar: "lol/misae.png",
              twitterLink: "",
              ytbLink: "",
              twitchLink: "",
              igLink: "",
            },
          ],
        },
      ],
    },
  ],
};
